config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :annonces, path: "achat-immobilier" do
    get :strasbourg, on: :collection
  end
  root to: "pages#home"
  get "contact", to: "pages#contact"
  post "contact_send", to: "pages#contact_send"

  get "achat-immobiler/strasbourg", to: "annonces#strasbourg"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/annonce.rb
class Annonce < ApplicationRecord
    has_many_attached :photos
    extend FriendlyId
    friendly_id :titre, use: :slugged
    monetize :price_cents
    geocoded_by :full_address
    after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @annonces = Annonce.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @annonces.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: {flat: flat})
      }
    end
  end

  def new
    @annonce = Annonce.new
  end

  def show
    @annonce = Annonce.friendly.find(params[:id])
    @markers = [{:lat=> @annonce.latitude, :lng=> @annonce.longitude}]
    #[{:lat=>49.0154694, :lng=>7.6205398
  end

  def create
    @annonce = Annonce.new(annonce_params)
    @annonce.town = @annonce.town.upcase
    @annonce.full_address = @annonce.address + "," + @annonce.town + "," + @annonce.cp
    @annonce.save
    redirect_to annonces_path
  end

  def edit
    @annonce = Annonce.friendly.find(params[:id])
  end

  def update
    @annonce = Annonce.friendly.find(params[:id])
    @annonce.update(annonce_params)
    redirect_to annonce_path(@annonce)
  end

  def destroy
    @annonce = Annonce.friendly.find(params[:id])
    @annonce.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to annonces_path, status: :see_other
  end

  def alsace
  end
  def bas_rhin
  end
  def strasbourg
    @annonces = Annonce.where(town: "STRASBOURG")
    @markers = @annonces.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: {flat: flat})
      }
    end
  end

  def annonce_params
    params.require(:annonce).permit(:titre, :town, :address, :cp, :full_address, :type_bien, :surface, :nbre_chambre, :nbre_bain,:balcon,:nbre_garage,:description,:nbre_cave,:cuisine,:surface_sejour,:etat_general,:etage,:nbre_etage,:type_chauffage,:type_cuisine,:annee_construction,:nbre_piece,:nbre_toilette,:nbre_etage_annonce,:mode_chauffage,:ascenceur,:price,:dpe,:vue_degagee,photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: []
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  skip_before_action :verify_authenticity_token

  def home
    @last_annonces = Annonce.last(4)
  end
  def contact
  end
  def contact_send
    contact = params[:contact_mail]
    if contact[:hidden_message].present?
      redirect_to request.referrer
    else
      if contact[:rgpd] == "positive"
        contact[:rgpd] = "oui"
      else
        contact[:rgpd] = "non"
      end
    end
  
    ContactMailer.with(status:contact[:status],type_demande:contact[:demande],email: contact[:email], lastname: contact[:lastname], firstname: contact[:firstname], tel: contact[:tel], message: contact[:message], rgpd: contact[:rgpd]).new_contact_email.deliver_later
    flash[:notice] = "Votre mail a été envoyé avec succès"
    redirect_to root_path 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annonces/_info_window.html.erb
<h2 data-poper-annonce=<%= flat.id %> ><%= flat.titre %></h2>
<p><%= flat.address %></p>

app/views/annonces/create.html.erb
<h1>Annonces#create</h1>
<p>Find me in app/views/annonces/create.html.erb</p>

app/views/annonces/destroy.html.erb
<h1>Annonces#destroy</h1>
<p>Find me in app/views/annonces/destroy.html.erb</p>

app/views/annonces/edit.html.erb
<h1>Annonces#edit</h1>
<p>Find me in app/views/annonces/edit.html.erb</p>

<section class="inside contact-form space-bottom">
    <%= simple_form_for(@annonce) do |f| %>
        <%= f.input :titre %>
        <%= f.input :address %>
        <%= f.input :town %>
        <%= f.input :cp %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%= f.input :type_bien %>
        <%= f.input :surface %>
        <%= f.input :nbre_chambre %>
        <%= f.input :nbre_bain %>
        <%= f.input :nbre_piece %>
        <%= f.input :dpe %>
        <%= f.input :ges %>
        <%= f.file_field :photos, multiple: true %>
        <%= f.button :submit %>
    <% end %>
</section>

app/views/annonces/index.html.erb
<h1>Annonces</h1>
<div id="filtres">
<ul>
<li>ville</li>
<li>type de bien</li>
<li>budget min max</li>
<li>nbre de pièces min_max</li>
<li>surface min_max</li>
</ul>
</div>
<section id="map-annonces">
<ul id="annonces">
<% @annonces.each do |annonce|%>
  <%= link_to annonce_path(annonce) do %>
    <li class="annonce" data-id=<%= annonce.id %> >
    <% if annonce.photos[0] != nil %>
    <%= cl_image_tag annonce.photos[0].key %>
    <% end %>
    <div class="annonce-card-description">
      <h3 class="annonce-titre"><%= annonce.titre%></h3>
      <p class="annonce-town"><%= annonce.town %></p>
      <p class="annonce-price"><%= annonce.price %> <%= annonce.price.currency.symbol %></p>
    </div>
    </li>
    <% end %>
  <% end %>
</ul>
<div id="map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</section>

app/views/annonces/new.html.erb
<h1>Annonces#new</h1>
<p>Find me in app/views/annonces/new.html.erb</p>

<section class="inside contact-form space-bottom">
    <%= simple_form_for(@annonce) do |f| %>
        <%= f.input :titre %>
        <%= f.input :address %>
        <%= f.input :town %>
        <%= f.input :cp %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%= f.file_field :photos, multiple: true %>
        <%= f.button :submit %>
    <% end %>
</section>

app/views/annonces/strasbourg.html.erb
<h1>Acheter un bien immobilier à Strasbourg</h1>
<div id="filtres">
<ul>
<li>ville</li>
<li>type de bien</li>
<li>budget min max</li>
<li>nbre de pièces min_max</li>
<li>surface min_max</li>
</ul>
</div>
<section id="map-annonces">
<ul id="annonces">
<% @annonces.each do |annonce|%>
  <%= link_to annonce_path(annonce) do %>
    <li class="annonce">
    <% if annonce.photos[0] != nil %>
    <%= cl_image_tag annonce.photos[0].key %>
    <% end %>
    <div class="annonce-card-description">
      <h3 class="annonce-titre"><%= annonce.titre%></h3>
      <p class="annonce-town"><%= annonce.town %></p>
      <p class="annonce-price"><%= annonce.price %> <%= annonce.price.currency.symbol %></p>
    </div>
    </li>
    <% end %>
  <% end %>
</ul>
<div id="map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</section>

app/views/annonces/update.html.erb
<h1>Annonces#update</h1>
<p>Find me in app/views/annonces/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marine Weishaar Immobilier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  </head>

  <body>
    <div class="sticky">
      <%= render "shared/header" %>
      <%= render "shared/navbar2" %>
    </div>
    <%= render "shared/flashes" %>
    <%= render "shared/mobilenav" %>
    <main>
      <article>
        <%= yield %>
      </article>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/contact.html.erb
<section>
<h1>Nous contacter</h1>
</section>
<section class="inside contact-form space-bottom center">
<%= simple_form_for :contact_mail, :url => '/contact_send' do |f| %>
  <h2>Nous contacter</h2>
  <div class="long">
    <%= f.input :status, label:"Vous êtes", collection:["Particulier","Professionnel"], input_html: { value: nil }, prompt: "", required: true %>
    <%= f.input :demande, label:"Votre demande concerne", collection:["Acheter","Vendre", "Louer","Gestion locative","Estimation","Autre"], input_html: { value: nil }, prompt: "", required: true %>
  </div>
  <div class="long">
    <%= f.input :lastname,label:"Nom", input_html: { value: nil }, placeholder: "", required: true %>
    <%= f.input :firstname,label:"Prénom", input_html: { value: nil }, placeholder: "", required: true%>
  </div>
  <div class="long">
    <%= f.input :email,label:"Email", input_html: { value: nil }, placeholder: "", required: true%>
    <%= f.input :tel,label:"Tel", input_html: { value: nil }, placeholder: "", required: true%>
  </div>
    <%= f.input :message,label:"Message", as: :text, input_html: {:rows => 5}, placeholder: "", required: true %>
    <%= f.input :rgpd, as: :boolean, checked_value: 'positive', unchecked_value: 'negative', required: true, label:"J'accepte que mes données soient transmises dans le cadre de ma démarche. En savoir plus sur notre politique de confidentialité" %>
    <p></p>
    <%= f.button :submit, 'Envoyer' %>
  <% end %>
</section>

app/views/pages/home.html.erb
<%= image_tag 'https://as1.ftcdn.net/v2/jpg/04/19/09/48/1000_F_419094889_eDaQJahzl1pBgKf8d0Xz0HoMCAt6DX8h.jpg', class: "banner"%>
<section class="inside">
</section>
<section class="inside space-bottom">
<h2>Nos derniers coups de coeur</h2>
<div class="grille four">
<% @last_annonces.each do |annonce|%>
  <div class="annonce">
  <% if annonce.photos[0] != nil %>
  <%= cl_image_tag annonce.photos[0].key %>
  <% end %>
  <div class="annonce-card-description">
    <h3 class="annonce-titre"><%= annonce.titre%></h3>
    <p class="annonce-town"><%= annonce.town %></p>
    <p class="annonce-price"><%= annonce.price%> <%= annonce.price.currency.symbol %></p>
  </div>
  </div>
<% end %>
</div>
</section>
<section class="inside space-bottom">
<h2>Nous avons la solution pour votre projet immobilier</h2>
<div class="grille three">
  <div class="item">
  <%= image_tag "acheter.png", class:"" %>
    <div>
    <h3>Acheter</h3>
    <p class="min-text">Faites votre choix parmis nos annonces ou confiez nous la recherche de votre futur logement<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
  <div class="item">
    <%= image_tag "vendre.png", class:"" %>
    <div>
    <h3>Vendre</h3>
    <p class="min-text">Confiez-nous l’estimation et la vente de votre logement au meilleur prix<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
  <div class="item">
    <%= image_tag "louer.png", class:"" %>
    <div>
    <h3>Louer</h3>
    <p class="min-text">Consultez nos nombreuses offres de location pour emménager sans délais<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
  <div class="item">
    <%= image_tag "syndic.png", class:"" %>
    <div>
    <h3>Home staging</h3>
    <p class="min-text">Valoriser votre bien pour la vente<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
  <div class="item">
    <%= image_tag "gestion-locative.png", class:"" %>
    <div>
    <h3>Gestion locative</h3>
    <p class="min-text">Notre agence s’occupe de la bonne gestion de votre patrimoine locatif<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
  <div class="item">
    <%= image_tag "investir.png", class:"" %>
    <div>
    <h3>Investir</h3>
    <p class="min-text">Investissez dans la pierre et bénéficiez d’avantages pour faire fructifier votre patrimoine<br>
    <%= link_to "En savoir plus" %></p>
    </div>
  </div>
</div>
</section>


<section class="inside contact-form space-bottom">
<%= simple_form_for :contact_mail, :url => '/contact_send' do |f| %>
  <h2>Nous contacter</h2>
  <%= f.email_field :hidden_message, placeholder: 'Message', class: 'hidden-message' %>
  <div class="long">
    <%= f.input :status, label:"Vous êtes", collection:["Particulier","Professionnel"], input_html: { value: nil }, prompt: "", required: true %>
    <%= f.input :demande, label:"Votre demande concerne", collection:["Acheter","Vendre", "Louer","Gestion locative","Estimation","Autre"], input_html: { value: nil }, prompt: "", required: true %>
  </div>
  <div class="long">
    <%= f.input :lastname,label:"Nom", input_html: { value: nil }, placeholder: "", required: true %>
    <%= f.input :firstname,label:"Prénom", input_html: { value: nil }, placeholder: "", required: true%>
  </div>
  <div class="long">
    <%= f.input :email,label:"Email", input_html: { value: nil }, placeholder: "", required: true%>
    <%= f.input :tel,label:"Tel", input_html: { value: nil }, placeholder: "", required: true%>
  </div>
    <%= f.input :message,label:"Message", as: :text, input_html: {:rows => 5}, placeholder: "", required: true %>
    <%= f.input :rgpd, as: :boolean, checked_value: 'positive', unchecked_value: 'negative', required: true, label:"J'accepte que mes données soient transmises dans le cadre de ma démarche. En savoir plus sur notre politique de confidentialité" %>
    <p></p>
    <%= f.button :submit, 'Envoyer' %>
  <% end %>
  <%= image_tag 'https://as2.ftcdn.net/v2/jpg/02/38/79/63/1000_F_238796325_jW2hwK0dds68xIscdYPTZ1XBQqvH6v4g.jpg' %>
</section>

app/views/shared/_annonce.html.erb
<div class="card" data-poper-annonce=<%= annonce.id %>>
<h3><%= annonce.titre %></h3>
<p><%= annonce.titre %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button"  data-controller="hello" data-action="click->hello#alertClose" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button data-controller="hello" data-action="click->hello#alertClose" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<div class="footer-content">
    <div class"footer-links">
        <a href="#">Mentions légales</a>
        <a href="#">Politique de confidentialité</a>
        <a href="#">Gestion des cookies</a>
        <a href="#">Plan du site</a>
        <a href="#">Ozymedia</a>
    </div>
    <%= image_tag "icones/logo-immomann-white.png", class: "logo-immomann" %>
</div>
</footer>

app/views/shared/_header.html.erb
<header class="header terra">
	<div>
	<%= link_to root_path do %>
		<%= image_tag "logo-mw.png", class:"logo" %>
	<% end %>
		<div class="boutons-header">
			<a href="" class="btn black">Mon espace pro</a>
			<%= link_to "Nous contacter", contact_path, class:"btn black" %>
			<i data-controller="hello" data-action="click->hello#mobile" class="fa-solid fa-bars" id="btn-mobile"></i>
		</div>
	</div>
</header>

app/views/shared/_mobilenav.html.erb
<ul id="mobilenav" class="">
<div>
    <%= image_tag "logo-mw.png", class:"logo" %>
</div>
<li>Test</li>
<li>Test</li>
<li>Test</li>
<li>Test</li>
<li>Test</li>
<li>Test</li>
<li>Test</li>
</ul>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<nav role="navigation" class="navbar2">
  <ul>
        <%= link_to annonces_path do %>
            <li>Acheter</li>
        <% end %>
        <li>Vendre
            <ul>
                <li>Estimer</li>
                <li>Sub Item1</li>
                <li>Sub Item1</li>
            </ul>
        </li>
        <li>Louer</li>
        <li>Gestion locative
            <ul>
                <li>Sub Item1</li>
                <li>Sub Item1</li>
                <li>Sub Item1</li>
            </ul>
        </li>
        <li>Home Staging</li>
        <li>Bureaux & commerces</li>
    </ul>
    <a href="">Déposer une annonce</a>
</nav>